sudo: false
language: node_js
node_js:
  - 8
cache: npm
branches:
  only:
    - source # build master source only
script:
  - hexo generate # generate static files
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  keep_history: true
  target_branch: master
  on:
    branch: source

  local_dir: public